metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ["logstash:9600"]
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
- module: system
  metricsets:
    - cpu
    - filesystem
    - fsstat
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - uptime
  enabled: true
  period: 10s
  processes: ['.*']
- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["http://kibana:5601"]
  username: "elastic"
  password: "changeme1"
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
  username: "elastic"
  password: "changeme1"
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
  username: "elastic"
  password: "changeme1"
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme1"
  ssl.enabled: true
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]
